### ISSUE TITLE
Javascript issue on fresh install

### ISSUE THREAD

**Issue by garethf89** [nathanwoulfe/Plumber-2#1]
I am getting the javascript error below when using a fresh installation of Umbraco 8 and installing Plumber 1.0.0 Beta.

The error occurs when I click the workflow tab on a Node.

angular.js?cdv=672968060:15536 TypeError: Cannot read property 'culture' of null

![Screenshot 2019-09-27 at 13 58 27](https://user-images.githubusercontent.com/5473451/65770939-0aa7ea80-e12f-11e9-9618-8fb3197e12ce.png)

**Comment by nathanwoulfe** [comment]
Ah yeah, I was a bit excited about managing variant content that I forgot to check what happens with invariant nodes... Turns out the content model doesn't include the default culture, instead culture is null. I need to add a check for that, and make the default culture available too.

**Comment by nathanwoulfe** [comment]
I've updated the beta release package, should be no more JS error if you update to build #000211.

**Comment by garethf89** [comment]
Thanks for the quick fix!
