### ISSUE TITLE
Errors on approval

### ISSUE THREAD

**Issue by garethf89** [nathanwoulfe/Plumber-2#10]
Hi Nathan,

Just reporting a couple more errors when clicking 'Approve'. Everything else seems fine for me now, thanks for the work you have put in to get this working @nathanwoulfe 

![Screenshot 2019-11-27 at 11 45 17](https://user-images.githubusercontent.com/5473451/69721423-b90ae480-110c-11ea-80c6-f8b7e666d910.png)
![Screenshot 2019-11-27 at 11 45 03](https://user-images.githubusercontent.com/5473451/69721430-bc9e6b80-110c-11ea-9815-043d656d78d2.png)

**Comment by nathanwoulfe** [comment]
Hi @garethf89, couple of quick questions
- are you on v1.0.6?
- umbraco version?
- are those errors related?
- how can I reproduce?

**Comment by garethf89** [comment]
Hi @nathanwoulfe , yeah its 1.0.6 on 8.2.0.

I successfully created an approval group in the workflow section.

I go to Home node, the first error randomly occurs when clicking 'Request Publish' and then 'Request Publish' without or with a message.

The second one happens every time, when I click Approve.

This is all with a workflow group with only myself.

**Comment by nathanwoulfe** [comment]
Has the group been assigned to the workflow on the home node? 

Sounds like it's probably related to having a single group in the workflow, will have a dig and see what I find

**Comment by garethf89** [comment]
Yeah it has been assigned

**Comment by nathanwoulfe** [comment]
Not sure how you'd be able to send for publish without a message - it's mandatory, so makes me think there's a JavaScript error. Second issue I've tracked down and will have a fix published this week - was related to checking for a culture on an invariant node.

**Comment by nathanwoulfe** [comment]
@garethf89 have a run with v1.0.7, I'm pretty sure this is working correctly now.

**Comment by garethf89** [comment]
Thanks @nathanwoulfe, I can now approve the workflow but still get this error if I leave 'Describe the changes' empty.

![Screenshot 2019-12-17 at 15 37 51](https://user-images.githubusercontent.com/5473451/71010238-72912000-20e3-11ea-903b-4e74661fa4be.png)

**Comment by nathanwoulfe** [comment]
I don't know how you're able to submit without a comment - the button should be disabled until a comment exists... Any console errors?

Steps to reproduce would be awesome

**Comment by garethf89** [comment]
Yeah there is no disabled state on the button. All seems good with a comment entered in the box though.

Steps:

Make Change on page,
Request Publish at the bottom
Request publish on next screen (no changes in the text box)
Error is shown

**Comment by garethf89** [comment]
i have upgraded to umbraco 8.4 now so that might have an impact on this
