### ISSUE TITLE
Unable to save settings using a test license

### ISSUE THREAD

**Issue by fransmilou** [nathanwoulfe/Plumber-2#108]
Unable to save settings

**To Reproduce**
1. Go to 'Workflow'
2. Click on 'Settings'
3. Fill out required fields.
4. Click on 'Save'
5. Se error.

**Expected behavior**
Settings should be saved

**Screenshots**
![image](https://user-images.githubusercontent.com/92791098/137895167-c6f8be54-0ebf-41c1-a750-f207068beecb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 94

**Plumber version**
2.0.1

**Licensed version?**
No (using a test.lic licence file)

**Additional context**

**Comment by fransmilou** [comment]
Hi @nathanwoulfe thanks, that issue was solved. But i have to ask should not a test.lic license enable all features if running on localhost? Currently we got this error if trying to att a doctype approval flow:

![image](https://user-images.githubusercontent.com/92791098/138088571-936d3bb2-36cd-4f9b-9e7b-17e57c0abedb.png)

So we have a hard time evaluate Plumber for our use-case without testing all features.

**Comment by fransmilou** [comment]
Great! it worked fine in debug mode. 

But unfortunately we can not test all features yet. We can´t change the Flow type. it fallbacks to 'Explicit' after we sucessfully saved the settings. (tested both Implicit and Exclude) we want to use the 'Implicit' setting.

![image](https://user-images.githubusercontent.com/92791098/138303062-89bae98b-54ef-402e-a418-b713515161ea.png)

**Comment by nathanwoulfe** [comment]
Fixed in 2.0.2
