### ISSUE TITLE
Error getting assigned instances for user id xx: Sequence contains no elements when view the editor Workflow dashboard

### ISSUE THREAD

**Issue by jesperweber** [nathanwoulfe/Plumber-2#109]
**Describe the bug**
Gets the followingen exception when viewing the editor Workflow dashboard. "Error getting assigned instances for user id xx: Sequence contains no elements"

The error started occurring on our production environment yesterday without any new deployment to the environment the last month.

**To Reproduce**
1. Visit the editor Workflow dashbaord

**Screenshots**
![image](https://user-images.githubusercontent.com/2575817/140048192-6bdecad2-6f50-43ea-a923-8339af1e6817.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 95

**Plumber version**
Plumber version 1.5.3

**Licensed version?**
We have a licensed version.

**Comment by nathanwoulfe** [comment]
Hey @jesperweber, few things to check:
- have any groups been deleted?
- have any users been deleted?
- is this happening for all users or just -1

Given there have been no code changes, it must be something in config/content. 

I'd recommend updating to the latest release too, there are a few bug fixes between 1.5.x and the latest 1.6.x. No reason not to go to the v2 release either.

**Comment by jesperweber** [comment]
Hi @nathanwoulfe, thanks for you reply.

From your questions I managed to reproduce the error on my local environment.

1. Create a group (no need to add members to the group)
2. Add the group as a content approval flow on a page
3. Request a publish
4. Delete the group
5. Now the editor Workflow dashboardet throws the exception

So it seems that deleting a group with pending approvals courses the exception.

Do you know if this is something that has been fixed? I will try to upgrade to see if it helps.

**Comment by jesperweber** [comment]
Just tried with version 1.6.8 and 2.0.2 and both versions has the same error.

**Comment by jesperweber** [comment]
BTW some nice changes in version 2 :-)

**Comment by nathanwoulfe** [comment]
Cheers @jesperweber, that's clear reproduction steps. It's not something I've fixed (I think the confirm group delete modal was a bandaid solution for cases like this). Shouldn't be a big deal to fix, just need to properly handle cases where the assigned group no longer exists, and skip that step of the workflow.

I'll deal with it for 2.0.3, which currently has no due date, haven't even bumped the version number in the repo 😄 

Did you get any other errors on the content node, particularly when viewing the workflow config tab? If the group is assigned, but deleted, I'm not sure how/if that's being managed...

Appreciate the v2 feedback too, definitely polishing things up a bit.

**Comment by nathanwoulfe** [comment]
Had a quick look, despite the overlay saying pending workflows will be cancelled when deleting a group, that doesn't actually happen, hence this error... Looks like I started with good intentions then promptly forgot to finish...

**Comment by jesperweber** [comment]
Sounds great with a fix in 2.0.3 and yes from the overlay it looks like you thought about the case :-)

I don't get any errors when viewing content node, even on the workflow config tab, so it seems like the case is handled there.

It's important that the fix will not only make sure that the error not will happen when deleting feature groups, but also handles the cause, like in our case, where the group is already deleted. From your description, it sounds like you will handle the case where the assigned group no longer exists, and skip that step of the workflow, so that's good.

Thanks for the reply and looking forward to version 2.0.3 :-)

**Comment by nathanwoulfe** [comment]
@jesperweber just a quick update - this was a bit larger than I expected, since it needs to also manage cleaning up group permissions to avoid blowing up when new workflows try to assign tasks to the deleted group. All under control, just took more effort than I expected.

**Comment by nathanwoulfe** [comment]
@jesperweber v2.1.0-rc is on nuget now. Bumped the minor as I've also updated the minimum V8 version to 8.16
