### ISSUE TITLE
Preview button in Workflow content app not working

### ISSUE THREAD

**Issue by Navorski** [nathanwoulfe/Plumber-2#110]
When a document is edited and "request publish" has been pressed, the approver wants to see what the document will look like. There is a preview button available

![image](https://user-images.githubusercontent.com/7352877/140959224-ca6ed486-b0fa-4643-a901-7e8a5241c107.png)

But when i press the button the page throws an error.

![image](https://user-images.githubusercontent.com/7352877/140958878-c70bcdb4-96d5-4747-9d66-9249e6e0e363.png)

while going to the page and preview it, it does not, and i can wee a difference in the URL between the preview from umbraco, and the preview from Plumber

https://localhost:44360/umbraco/preview/?id=1087#?culture=undefined

The moment i manually remove the ?culture=undefined then the preview is working.
So it does have something to do with the cultures on the document. (this site has no english language, only 1 language, dutch)

**Comment by nathanwoulfe** [comment]
Hey @Navorski thanks for letting me know - will fix this for the next release. Looks like I always need to pass the culture param with a valid value

**Comment by nathanwoulfe** [comment]
Fixed in v2.0.0-rc
