### ISSUE TITLE
Filter users not working

### ISSUE THREAD

**Issue by jesperweber** [nathanwoulfe/Plumber-2#111]
**Describe the bug**
When adding members to an approval group, the filter is not working. Filtering groups works just fine.

**To Reproduce**
1. Create an approval group
2. Click 'Add' on Group members
3. Enter a search term in the "Type to filter..." field
4. See that the list of users are not filtered

**Expected behavior**
From the filter on the screenshot below I would only expect to see users hows name contains "aksel"

**Screenshots**
![image](https://user-images.githubusercontent.com/2575817/143004855-9b4a28b4-5e00-4ec6-baf4-fd6b1a44e8ac.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Plumber version**
2.0.2

**Licensed version?**
We have a licens

**Additional context**

**Comment by nathanwoulfe** [comment]
Hey @jesperweber I have a feeling this is an Umbraco issue, vaguely remember seeing a related big. I think it's due to the filter applying to the entire user object rather than just the name property. 

Will have a proper look in the morning, I have a bit of stuff to wrap up for 2.1.0, so can include this if it needs a Plumber fix

**Comment by jesperweber** [comment]
Hey @nathanwoulfe Sounds great. 

If I go to the Users section in Umbraco, the Umbraco filter works fine on the user list. But, don't know how much Plumber relies on the Umbraco core.

**Comment by nathanwoulfe** [comment]
@jesperweber bit of a strange one - in Umbraco 8.16.0 the user picker doesn't filter in the Users section either (for me at least). Plumber uses the core UserPicker on EditorService, so nothing custom, but there might be config missing from my implementation. Doesn't explain though with the filter in Users isn't working...

**Comment by nathanwoulfe** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/11605 => will be part of 8.18, not sure if it's been merged up into v9. Definitely doesn't work in Plumber on V8, haven't checked on V9.

**Comment by jesperweber** [comment]
Ahh, so the Umbraco issue you are linking to is about the filtering in the user picker, which Plumber uses. I was testing the Umbraco filter function in the users section and this work. 

![image](https://user-images.githubusercontent.com/2575817/143200649-7fdf48eb-0c58-4fde-a78d-90fffc06705a.png)

I think you are right that this is not a Plumber issue but an Umbraco issue which will be fixed in 8.18.0 :-)

**Comment by nathanwoulfe** [comment]
Yup, that explains it - the filter in the userpicker has been broken for at least 14 months (that was the last change prior to the bug being fixed), surprising it took that long for anyone to realise!

Picker really should be paginated too, bit that's a whole other conversation...

**Comment by jesperweber** [comment]
Haha, that's a long time.

Well thanks for helping sorting this out :-)

**Comment by nathanwoulfe** [comment]
Will be fixed when the underlying issue is resolved in Umbraco, hopefully not too far away.
