### ISSUE TITLE
plumber2 migration Umbraco boot failed Exception

### ISSUE THREAD

**Issue by gurumurthyjv** [nathanwoulfe/Plumber-2#113]
HI @nathanwoulfe ,

We also, have an similar issue with plumber 1.6.8 on Umbraco 8.14.

We have installed it through nuget in DEV environment, and we have deployed the code changes to our UAT (both DEV and UAT are 2 different environments with different DB's) and we are getting boot failed Umbraco exceptions. Below are some of the logs attached. This exception is from plumber migration as per logs.

Could you help us on how can we resolve this issue.

Also, how to migrate the plumber 2 between environments ? do we need to install gain on higher environments ? as its has separate DB.

`D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:line 67\r\n   at Plumber.Web.Migrations.WorkflowInstallMigration.Execute() in D:\\a\\1\\s\\Plumber.Web\\Migrations\\WorkflowInstallMigration.cs:line 40\r\n   at Plumber.Web.WebComponent.Initialize() in D:\\a\\1\\s\\Plumber.Web\\Components\\WebComponent.cs:line 64\r\n   at `

`{"@t":"2021-12-30T16:30:02.9029982Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Data.SqlClient.SqlException: CREATE TABLE permission denied in database 'uat-sqldb'.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at `

Thanks,
Gurumurthy J V

_Originally posted by @gurumurthyjv in https://github.com/nathanwoulfe/Plumber-2/issues/48#issuecomment-1003276891_

**Comment by nathanwoulfe** [comment]
Looking at the trace this appears to be a permissions issue - the required tables haven't been created hence the boot failure. It's a database problem, not specific to Plumber - check the connecting account has db_owner permission in your database. 

The package manages installation on different environments. So long as the DLLs are deployed, the install process will run once only, when the site starts. That process includes creating database tables, which relates to the log you've shared. 

I'd recommend upgrading to v2.1, there is no further development on the v1 branch, and is missing a lot of new stuff added for v2.

**Comment by gurumurthyjv** [comment]
Thanks for the response @nathanwoulfe ,

Will check the permission issue, and will re-try it.

Thanks,
