### ISSUE TITLE
Workflow history preview link is wrong

### ISSUE THREAD

**Issue by callumbwhyte** [nathanwoulfe/Plumber-2#12]
The "preview" link against tasks in the "Workflow history" dashboard (in the "Workflow" section) points to a path that no longer exists... `/umbraco/dialogs/preview.aspx?id=XYZ?cculture=`

The new preview URL is: http://h4h.local/umbraco/preview/?id=XYZ

However this seems inconsistent with elsewhere in Plumber, as on the "Workflow" dashboard (in the content section) links to the content item itself within the CMS.

**Comment by nathanwoulfe** [comment]
Yup, that should be a link to the content item. Have fixed, will be in the next release.

**Comment by nathanwoulfe** [comment]
fixed in v1.1.0
