### ISSUE TITLE
Umbraco 9.3.1 Offline Approval not working

### ISSUE THREAD

**Issue by EM-Benji** [nathanwoulfe/Plumber-2#124]
**Describe the bug**
Setup Plumber and do an offline approval locally then I get a blank white bar at the bottom of the page with console errors

```
Uncaught ReferenceError: angular is not defined
    at Object.1../action-workflow/action (plumber-offline.js:25:28)
    at o (plumber-offline.js:1:265)
    at plumber-offline.js:1:316
    at Object.42.../components/_componentsModule (plumber-offline.js:3340:29)
    at o (plumber-offline.js:1:265)
    at r (plumber-offline.js:1:431)
    at plumber-offline.js:1:460
```

```
Uncaught ReferenceError: angular is not defined
    at plumber-offline-loader.js:22:5
    at i (lazyload.min.js:1:214)
    at HTMLScriptElement.p (lazyload.min.js:1:541)
```
This is cause the plumber-offline-loader is requesting some files with non ".min.js" urls which don't exist.

Editing those urls to have the required .min made progress but ran into other issues like 

Umbraco.Sys.ServerVariables.Plumber.platform and  Umbraco.Sys.ServerVariables.Plumber.license not being defined. Also /umbraco/backoffice/signalr/hubs is 404 but that i think is due to the platform not being set.

plus on rebuild these chances get wiped.

I also have the header X-Content-Type-Options: nosniff set as well if that might be making a different.

**Expected behavior**
Offline approval to show options to approve or reject and workflow

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge 
 - Version: 99.0.1150.4
 - Umbraco: 9.3.1

**Plumber version**
2.1.3

**Licensed version?**
No

**Additional context**

**Comment by nathanwoulfe** [comment]
Hey @EM-Benji I'll have a look at this tomorrow - the offline stuff has always been super flakey, it probably shouldn't work at all...

**Comment by EM-Benji** [comment]
Hi @nathanwoulfe yeah it was temperamental at times in v7 too. thanks for looking into this.

**Comment by nathanwoulfe** [comment]
@EM-Benji so this was super broken! Having to target 8 and 9 makes it even more fun to fix, but looks like I've got it sorted. Will test a bit more, then aim for a patch in a week or so.

**Comment by EM-Benji** [comment]
@nathanwoulfe thanks for the quick response. that's great news

**Comment by nathanwoulfe** [comment]
@EM-Benji 2.1.4 is available now, should be all good again with offline approval
