### ISSUE TITLE
Update Message when updated to latest version

### ISSUE THREAD

**Issue by johncscott** [nathanwoulfe/Plumber-2#135]
Getting an update message
![image](https://user-images.githubusercontent.com/839694/191931530-2ccf5e7a-bef8-4a4e-94ae-15d869cb1299.png)
after having already updated to latest version with nuGet.
This is the packages.config:
![image](https://user-images.githubusercontent.com/839694/191931781-5f715ba7-4dcb-4690-96b9-09196ada284a.png)

This is using Umbraco v8.18.0 as a standalone installation (not cloud) on Azure.

**Comment by nathanwoulfe** [comment]
Hi @johncscott I need to update that message - 8/9 will always be the latest v2 release.

That message should be gone next time the cache period expires (or when the site restarts). I hadn't correctly tagged the v2.1.8 release, so GH was returning 2.1.7 as the latest 8/9 compatible version.
