### ISSUE TITLE
Workflows on no longer existing nodes

### ISSUE THREAD

**Issue by johncscott** [nathanwoulfe/Plumber-2#136]
![image](https://user-images.githubusercontent.com/839694/191930745-430297e7-3e06-4f37-8a96-ee0707218441.png)
We have a number of workflow items that relate to nodes that have been deleted
I'd like to create an on delete trigger that prevented this from happening what is the best way to check if there is a current unresolved workflow?
Also what is the best way to remove these workflow items now? Details etc. nothing works and there is no way to navigate to them

**Comment by nathanwoulfe** [comment]
Hi @johncscott, is this also on 8.18? There should be a cleanup job run automatically when deleting a node, I'll need to check that is working correctly.

In the short term if you want to clean these up manually, you'd need to delete entries from WorkflowInstance and WorkflowTaskInstance tables, using the node id to find the correct instance guid to delete.

**Comment by johncscott** [comment]
amazing - thank you Nathan - very much appreciated

**Comment by nathanwoulfe** [comment]
Hey @johncscott v2.1.9 is on Nuget now, this error should be fixed in that release.
