### ISSUE TITLE
Request errors when submitting/rejecting requests

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#14]
Hi Nathan,

I've just installed the latest (non-beta) release to an Umbraco 8.5.5 site and set up a test approval group.
When I submit a request I'm getting the following 3 pop-ups showing:

![image](https://user-images.githubusercontent.com/13313745/79447478-d109d480-7fd7-11ea-99de-d8d4e8710d8f.png)

This also happens when rejecting/resubmitting a workflow request.

**Comment by nathanwoulfe** [comment]
@NikRimington I haven't been able to reproduce this one - try bumping to v1.2.0 and see if it persists. The undefined route param should be the guid identifying the workflow, not sure how that would be undefined when there's obviously an active workflow (given the success notification)...

**Comment by nathanwoulfe** [comment]
This should be ok in the latest version - never found a cause, but saw not issues in testing for the 1.2/1.3 releases
