### ISSUE TITLE
JS errors from Overview chart

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#15]
When clicking on one of the items at the top of the WorkFlow section of the site:

![image](https://user-images.githubusercontent.com/13313745/79448016-a8cea580-7fd8-11ea-9455-514bbfcf8ea9.png)

A white screen loads and a JS error occurs in the console error:

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at getActivity (plumber.js?cdv=256162187:2125)
    at historyController (plumber.js?cdv=256162187:2136)
    at Object.invoke (angular.js?cdv=256162187:5122)
```

**Comment by NikRimington** [comment]
Umbraco 8.5.5
Plumber 1.1.3

**Comment by nathanwoulfe** [comment]
@NikRimington I'll confirm this is still an issue in the latest code - have revised that dashboard a bit, so hopefully no more error. I've removed the clickability of those header boxes, it didn't make sense to click through to a new chart when the existing view can be filtered by clicking the axes (I think...)

**Comment by nathanwoulfe** [comment]
@NikRimington if you have a chance to install the latest nightly, this has been resolved.

**Comment by nathanwoulfe** [comment]
all sorted in v1.2. I think.
