### ISSUE TITLE
Question: Should an explicit workflow still show inherited work flow?

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#16]
I've added an explicit workflow to a sub page of a root node (that has a workflow set on it)
However, on the Workflow content app, it still says it is using the inherited approval flow, should it not hide the section highlighted in red, if an explicit flow is set in the area highlighted in blue?

![image](https://user-images.githubusercontent.com/13313745/79448887-234bf500-7fda-11ea-9ef6-7e4b814d7a58.png)

**Comment by nathanwoulfe** [comment]
Hi @NikRimington, that's dodgy UI on my part - it will be applying the explicit workflow, the inherited one is shown only as an FYI. I'll update the header on the green card to include a badge with ACTIVE text, and similar on the inherited, with INACTIVE.

**Comment by nathanwoulfe** [comment]
v1.2
