### ISSUE TITLE
Where can I download the Plumber for Umbraco 8?

### ISSUE THREAD

**Issue by eickegao** [nathanwoulfe/Plumber-2#17]
Hi Nathan,
I tried to download the Plumber for Umbraco 8. But I can not find the build in this repo.

Could you share the download URL to me?

Thanks,
Gao

**Comment by nathanwoulfe** [comment]
Hi @eickegao it's a nuget install only for v8, package is named Plumber.Workflow

**Comment by eickegao** [comment]
Hi Nathan,
Thank you for the help.
Still have a question. I have an Umbraco 8 website. How could I install this workflow? Should I get the package from nuget and zip the file then install in the Umbraco 8? Never did that before.

Thanks,
Gao

**Comment by eickegao** [comment]
Hi @nathanwoulfe 
Thank you for the help.
Still have a question. I have an Umbraco 8 website. How could I install this workflow? Should I get the package from nuget and zip the file then install in the Umbraco 8? Never did that before.

Thanks,
Gao

**Comment by Chris-N1** [comment]
Hi @eickegao 

To install via nuget you need to use Visual Studio to run the command that Nathan mentions - there are also instructions here:

https://www.nuget.org/packages/Plumber.Workflow

Hope that helps!

**Comment by eickegao** [comment]
Hi @nathanwoulfe 
I understand I need the nuget and vs to install this.
Do you mean I just need to install the Visual Studio and run the command in the VM which I has the existing Umbraco?
Because for Umbraco 7 I need to download the package and install that file in local. I have never run the command line to install the Umbraco 8 plugin.

Thank you for all the help.

Thanks,
Gao

**Comment by Chris-N1** [comment]
Hi @eickegao 

You will need Visual Studio and your website loaded as a visual studio project; nuget is included with visual studio. 

You can use the package manager inside visual studio to install packages from nuget.

If your site is only remote (e.g. if you only use Umbraco Cloud or your site is on remote hosting) then this might not be possible - you can't install a nuget package via Umbraco's back office.

**Comment by eickegao** [comment]
@Chris-N1 
Thank you very much. I am also a developer. But I am new to Umbraco.
I have the website in the Azure VM. Here are what I need to do?
1 Install the VS in that Azure VM.
2 Load the website as the project.
3 install the plumber via the nuget.
4 compile that project and deploy it into the VM again.
Is that the right steps I need to follow? If yes I will start to work on it.

Thanks,
Gao

**Comment by Chris-N1** [comment]
Hi @eickegao,

Apologies for the delay, work is a bit manic right now. I've never used a VM in Azure for development, but if you have access to all of the required files then yes, that is what you would need to do; my own process for a new site (on my local machine) is usually:

1) Create a new empty ASP.Net project in Visual Studio
2) Install Umbraco via Nuget
3) Set up document types & views
4) Develop & test

If the website already exists I would probably import views etc. into the project after step 2), but this won't create document types - you'd need to ensure that the project points at the correct database to work with the views (note that none of this has anything to do with Plumber - you'd be best off looking at https://our.umbraco.com/download/ )

**Comment by nathanwoulfe** [comment]
I'll probably make a backoffice package available at some point, but there will be issues with managing dependencies (Plumber has a couple, easily managed with nuget, not so with a package).

**Comment by eickegao** [comment]
If there is a package for install that will be great.
