### ISSUE TITLE
Licensing not working

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#18]
We are running on Azure, in a multi web app configuration; we have a back office server set up for editing and 2 extra servers to take traffic from different places, but users cannot log on to the back offices for these servers

Plumber 1.2.0 beta-0344 is installed. (There was a bug in 1.1.3 which prevented us using it).

We only need the most basic functionality (3 approval groups, inherited explicit workflows only), although I'm hoping I can get the client to upgrade to a commercial license at some point.

This was previously working fine; however, after pushing 1 minor change tonight (which had nothing to do with Plumber) suddenly the "it looks like you're new here" message is popping up all over the place.

Trying to create a Trial subscription via the back office does not work - I can fill in the details but clicking the "add subscription" button does nothing - I don't even get an error.

I've tried re-publishing the existing license files and recycling the app pool, and republishing from VS - nothing has had any effect.

The same license is showing up as valid when I run locally.

Any ideas?!

**Comment by Chris-N1** [comment]
This appears to have resolved itself, although I frankly have no idea how or why - license is suddenly showing up again.

**Comment by nathanwoulfe** [comment]
Glad to hear it - was mid-message when your comment dropped in. I'll check the licensing server, there may have been an outage at that end... Although that shouldn't matter, because the licensing server is only hit on generating the license and checking once a month that a valid subscription still exists...

Bit strange, but glad to hear it's working. Let me know if you track down the cause...

**Comment by Chris-N1** [comment]
It was rather strange - a couple of hours of swearing and restarting the back office and then suddenly it decided all was well.

There's definitely an issue in 1.2.0 with creating a license though - even locally, looking at the console there's an error that "form is not defined" if I move the .lic and .key files and try to create a new license:

![image](https://user-images.githubusercontent.com/46811766/81996026-e3f9de00-9643-11ea-8997-5506e0669204.png)

**Comment by nathanwoulfe** [comment]
Ah, so there is - part of 1.2.0 is a full refactor to es6 modules, still finding a few places where I've missed syntax changes. Will sort this one
