### ISSUE TITLE
Error on selecting a Node

### ISSUE THREAD

**Issue by garethf89** [nathanwoulfe/Plumber-2#2]
The below issue occurs on a fresh installation when clicking on any node, I have not yet been able to set up any Workflows or do anything in Plumber.

![Screenshot 2019-09-30 at 11 17 17](https://user-images.githubusercontent.com/5473451/65870460-336cf180-e374-11e9-9ba7-9235cd138d91.png)

**Comment by nathanwoulfe** [comment]
Anything in logs? If you have access to the workflow section, try filling in the workflow settings info, and creating a group, adding users, then accessing a node.

I haven't worked from a clean install in a while so could be related to plumber expecting values that may not yet exist. Will do a fresh install and see if I can reproduce.

**Comment by garethf89** [comment]
I have created a group and added a user, then this appears when I click on a node.

**Comment by garethf89** [comment]
This is in the console: 

`angular.js?cdv=191073365:15536 Possibly unhandled rejection: {"errorMsg":"Something broke","data":{"ExceptionType":"NullReferenceException","ExceptionMessage":"Error getting node config","StackTrace":"   at Plumber.Web.Api.ConfigController.GetNodeConfig(Int32 id, Int32 type, String path, String variant)"},"status":500}`

This is in umbraco logs

`{"@t":"2019-09-30T13:48:46.4121326Z","@mt":"Error getting node config","@l":"Error","SourceContext":"Plumber.Web.Api.ConfigController","ProcessId":8052,"ProcessName":"iisexpress","ThreadId":63,"AppDomainId":6,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"HG-W-RES-VM-01","Log4NetLevel":"ERROR","HttpRequestNumber":3,"HttpRequestId":"8239ed22-c2b3-40db-b308-b2bf84c3533b"}
`

**Comment by nathanwoulfe** [comment]
Found the issue, will update the beta build and ping you when it's available.

Probably should make those logged messages a bit more useful too...

**Comment by nathanwoulfe** [comment]
Have added a new beta, give it a try.

**Comment by garethf89** [comment]
Hi Nathan, thanks for helping with this! Not getting any errors now but getting one on publish. 

Thanks for your help with this, hoping to use this in a new project im working on to avoid using the outdated Umbraco 7.
