### ISSUE TITLE
User can not pay

### ISSUE THREAD

**Issue by Jonroberts24Swansea** [nathanwoulfe/Plumber-2#23]
Hi 
Our client, once finally logged into the CMS, is now getting this error (see attached image) when he is trying to pay:
"Now when I try to purchase the Plumber License and I click on the ‘pay’ button I get the following error before I have the chance to put in my card details."

Is he not doing something or is this an error your end?

Many thanks
Jon
![Plumber-error](https://user-images.githubusercontent.com/67054272/84892813-2aed5000-b096-11ea-8be2-e6b273a849e6.jpg)

**Comment by nathanwoulfe** [comment]
Hey Jon, I'll have a look at this today. 

Clicking pay _before_ entering card details sounds a bit odd - makes me think I might need to improve the UX (maybe disabling the button until the form is valid)

N

**Comment by nathanwoulfe** [comment]
@Jonroberts24Swansea hold fire - I'm going to rework the whole payment flow, I'm not happy with how it works (overly complicated for me and for users). Will let you know when it's sorted.

**Comment by nathanwoulfe** [comment]
@Jonroberts24Swansea this should be fine now - I've completely re-done the payment flow and licensing model. It's all a lot simpler now 😄
