### ISSUE TITLE
Upgrade Issues?

### ISSUE THREAD

**Issue by mhersh82** [nathanwoulfe/Plumber-2#26]
Hi Nathan,

We're currently in a trial mode with Plumber 2, on the verge of buying a long term license, but have run into issues with each of the last two updates.  Is it expected that new versions will usually break older versions?  We're on a sprint release cycle, so our posts don't happen daily, and thus we'd be stuck with production errors until our next release.  We're also allowing our clients to curate content, and are hoping that there's a way to suppress the error and upgrade messages from showing up in the UI.  Is there, or can there be, any flexibility with that?  Before we purchase a license, we just want to confirm what options we have.  Here's the error we're currently seeing:

![image](https://user-images.githubusercontent.com/4008347/85406489-e77c6100-b52f-11ea-9361-ea6678447155.png)

I did just notice the last line of the upgrade message on the workflow tab:  Upgrading from earlier versions is encouraged (more heartily than usual), as old third-party API endpoints no longer exist and will surface errors in the backoffice.

Maybe that's the issue this time, but I do know we were getting errors in the UI when the previous version was posted, too.  That was before we got around to upgrading, and then upgrading resolved the issues.  Please let me know your thoughts.

Thanks.

**Comment by nathanwoulfe** [comment]
Hi @mhersh82 that error doesn't look to be related to any of the recent changes - error is thrown in GetContentNameById, so I'm guessing it's not managing cases where content no longer exists. I'll look into it.

As for the breaking changes in the 1.3.0 release, those were restricted to only the licensing view in the workflow section, they won't impact the rest of the application, or the functionality within Plumber. The removed APIs were tasked with fetching information about, and generating subscriptions on a third-party server, so unless you're in the workflow/licensing section, the errors won't surface. These were absolutely out-of-cycle changes, and not the norm.

I'd never expect a version release to introduce errors - whole intent of releasing updates is to fix, not break things. That said, it's a project of growing complexity, having to cater to different Umbraco versions and environments. If you have issues, please raise them here to provide visibility.

ta
Nathan

**Comment by nathanwoulfe** [comment]
Fix for this error will be in the next nightly, if you're able to install to verify - I've changed handling for deleted nodes to allow them to appear in history/charts.

Will release 1.3.5 in the next day or two.

**Comment by mhersh82** [comment]
Thanks for the quick response, Nathan!  I'll try to give that a go later today.

**Comment by nathanwoulfe** [comment]
Next day or two became 9 days (had some betas in between 😄 )

1.3.5 is building now.
