### ISSUE TITLE
No notification on reject

### ISSUE THREAD

**Issue by Sjoerdson** [nathanwoulfe/Plumber-2#27]
Hi,

We are currently testing your plugin and overall it works great. We only came accross one 'issue':

When an approver rejects the changes of an author, the author doesn't receive an e-mail notification. In all other cases (approval requested, cancel, approval), either the author or the approver get an e-mail notification, if enabled of course. Only in case of reject no notification seems to be sent. 

It would be great if this could be fixed. 

Thanks.

**Comment by nathanwoulfe** [comment]
Hi @Sjoerdson thanks for letting me know - will be an easy fix, I'll include it in the next patch.

**Comment by nathanwoulfe** [comment]
Fixed in v1.3.5
