### ISSUE TITLE
Content not always saved when submitting

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#28]
A client has raised this one; they're using 1.2.1, but I've verified that the issue is still present in 1.3.4 locally.

When the user clicks "Request Publish" the message stating that the content has been saved pops up and the publish request is submitted to the approval group, but the document has not changed when it gets to the approval group - screenshots below:

Editing page (this is Nested Content, in case that makes a difference):

![image](https://user-images.githubusercontent.com/46811766/85713576-695fbc00-b6e1-11ea-99c3-a0d9c1ef41b4.png)

Submitting:
![image](https://user-images.githubusercontent.com/46811766/85713749-990ec400-b6e1-11ea-8ee3-798251253b98.png)

(Note - the message appears to say the content has been saved at this point)

Warning appears when logging out:

![image](https://user-images.githubusercontent.com/46811766/85713774-a0ce6880-b6e1-11ea-8be1-6507e4d81d7f.png)

Logged in as an administrator in the approval group, on the same page the edited content has vanished:

![image](https://user-images.githubusercontent.com/46811766/85713916-cb202600-b6e1-11ea-84d2-0612ec3ce0b1.png)

**Comment by nathanwoulfe** [comment]
Hi Chris, this might actually be related to nested content - from memory, there's something funky going on with the way NC binds data. Could you check in a different, non-NC property and confirm that save does/doesn't happen correctly? 

I vaguely remember a similar issue in Preflight, where checking dirty content wasn't flagging NC, might need to resolve this similarly...

**Comment by Chris-N1** [comment]
Hi Nathan,

Thanks for the speedy response - I think you could be right; I tried it with another bog-standard RTE that's not part of an NC element and it was fine.

**Comment by nathanwoulfe** [comment]
I guess that's a good thing 🙄

Pretty sure it's related to NC not actually dirtying the content form. I've dealt with it in other packages, will do the same here.

**Comment by nathanwoulfe** [comment]
Hi @Chris-N1 

Definitely related to how nested content works - it only syncs back to the content model in certain scenarios, none of which were being triggered by Plumber saving the content. 

It's not the most elegant solution, but it works: fix is to programmatically close any open NC panels, which triggers the sync handler and updates the content model. Bit clunky, but does the job.

This fix will be available in the next nightly build (around 6 hours from the time of this comment). Will leave this open, if you could install the nightly and verify the solution works.

**Comment by Chris-N1** [comment]
Thanks Nathan - I'll take a look and get the client to test in their UAT site tomorrow (it's Sunday morning here - kudos on your dedication to the cause!) :).

**Comment by Chris-N1** [comment]
Hi Nathan - that seems to have fixed it - I'll get the client to test in our dev environment, but it seems fine locally :)

Thanks,

Chris.

**Comment by nathanwoulfe** [comment]
Excellent, glad to hear it - I'll have a proper 1.3.5 release out soon, trying to iron out a couple of other bugs first.

**Comment by Chris-N1** [comment]
Cool - there seems to be another unrelated issue at the moment, when I try to log in to the back office on our Dev site this error is occurring in the log that seems to stop the entire back office loading - this is the only message in the log. It's working locally so I assume it must be a configuration thing but I can't seem to find what I need to change....any clues?!

{"@t":"2020-07-01T08:22:36.8750523Z","@mt":"An unhandled exception occurred","@l":"Error","@x":"Newtonsoft.Json.JsonSerializationException: 
Error getting value from 'IsLicensed' on 'Plumber.Core.Models.Licensing.PlumberLicense'. 
---> System.UriFormatException: Invalid URI: The hostname could not be parsed.\r\n   
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)\r\n   at System.Uri..ctor(String uriString)\r\n   at Plumber.Core.Models.Licensing.PlumberLicense.IsLicensedDomain()\r\n   at Plumber.Core.Models.Licensing.PlumberLicense.get_IsLicensed()\r\n   at GetIsLicensed(Object )\r\n   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target) in /_/Src/Newtonsoft.Json/Serialization/DynamicValueProvider.cs:line 110\r\n   
--- End of inner exception stack trace 
---\r\n   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target) in /_/Src/Newtonsoft.Json/Serialization/DynamicValueProvider.cs:line 114\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 520\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 469\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 173\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 1089\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 194\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs:line 95\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 1149\r\n   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 1889\r\n   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JObject.cs:line 489\r\n   at Umbraco.Web.JavaScript.ServerVariablesParser.Parse(Dictionary`2 items) in D:\\a\\1\\s\\src\\Umbraco.Web\\JavaScript\\ServerVariablesParser.cs:line 18\r\n   at Umbraco.Web.Editors.BackOfficeController.<>c__DisplayClass19_0.<ServerVariables>b__0() in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\BackOfficeController.cs:line 268\r\n   at Umbraco.Core.Cache.AppCacheExtensions.<>c__DisplayClass0_0`1.<GetCacheItem>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\AppCacheExtensions.cs:line 22\r\n   at Umbraco.Core.Cache.FastDictionaryAppCacheBase.<>c__DisplayClass21_0.<GetSafeLazy>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\FastDictionaryAppCacheBase.cs:line 285\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Umbraco.Core.Cache.WebCachingAppCache.GetInternal(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\WebCachingAppCache.cs:line 173\r\n   at Umbraco.Core.Cache.WebCachingAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\WebCachingAppCache.cs:line 40\r\n   at Umbraco.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)\r\n   at Umbraco.Web.Editors.BackOfficeController.ServerVariables() in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\BackOfficeController.cs:line 264\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()\r\n   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)\r\n   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)\r\n   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","SourceContext":"Umbraco.Web.UmbracoApplicationBase","ProcessId":5760,"ProcessName":"w3wp","ThreadId":77,"AppDomainId":5,"AppDomainAppId":"LMW3SVC1024150556ROOT","MachineName":"RD28187852F999","Log4NetLevel":"ERROR","HttpSessionId":"wkqzawnblfsigcquolssbkgd","HttpRequestNumber":4,"HttpRequestId":"a618381a-8f18-49cf-8e30-09e9d967a39a"}

**Comment by nathanwoulfe** [comment]
What's the hostname for the Dev site? Would you be able to share the license file?

There's an issue there with checking the licensed domain against the current hostname. Haven't seen that before though...

**Comment by nathanwoulfe** [comment]
Quick fix too might be to rename the license file to test.lic - that should bypass the domain checks and prevent the error

**Comment by Chris-N1** [comment]
Hi Nathan,

Is there a way to message you privately? (I can't see a way here or on your website) 

The name of the client is in the URL and they're a third-party's client and it's confidential (I know, I know - the joys of being freelance) - it's an azurewebsites.net domain though in case that helps.

I tried changing the license file name but it didn't make any difference :(.

**Comment by nathanwoulfe** [comment]
sure - email to nathan@nathanw.com.au. 

did you restart/recycle after renaming the file? need a restart to re-check the license. having said that, if it's not a paid license you should be able to delete the license completely, since 1.3.4+ uses a new licensing strategy...

**Comment by Chris-N1** [comment]
Aha - deleting the license files and editing the web.config to force a recycle seems to have done the trick!

Many thanks - I can ask the client to try testing the save changes now.

**Comment by nathanwoulfe** [comment]
Happy days. Always good to fix issues by deleting stuff 😄
