### ISSUE TITLE
Plumber says it's out of date after installing 1.3.5

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#29]
I don't suppose this matters in terms of functionality but thought you might like to know - after installing 1.3.5 I got this message on the Workflow tab:

![image](https://user-images.githubusercontent.com/46811766/86583097-9716f180-bf7a-11ea-8d4c-64ea894803bc.png)

**Comment by nathanwoulfe** [comment]
That's my bad - typo in the release tag, it's fixed now. That value is fetched from the repo and cached for six hours, so will update eventually.
