### ISSUE TITLE
Missing "Request Unpublish" button

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#31]
Hi Nathan - sorry, me again!

Since 1.2.0 or so the "Request Unpublish" button has vanished; I'm not sure if this is to do with our configuration, but our settings seem to be OK and haven't changed since we migrated from version 7.

We have an "Editors" group that looks like this:
![image](https://user-images.githubusercontent.com/46811766/87296764-2b470280-c4ff-11ea-9b25-b0921afde041.png)

In the earlier version of Plumber for v7 this would result in a "request unpublish" item being available via the popup "request publish" button in the bottom right, but this doesn't seem to appear any more - the menu option only appears if I'm logged in as an admin or somebody in the approval group (the approval group have "Super Editor" privileges and can unpublish the node directly).

This is what I see when logged in as a member of the editors group:

![image](https://user-images.githubusercontent.com/46811766/87296992-9c86b580-c4ff-11ea-85c4-2050443ae5e2.png)

Adding the "Unpublish" permission to the Editors group doesn't make any difference - neither the "Unpublish" or "Request Unpublish" buttons appear. 

It might be there's some combination of permissions that would stop a user directly publishing whilst keeping them able to unpublish but I don't seem to be able to find it!

Thanks,

Chris.

**Comment by nathanwoulfe** [comment]
Hi Chris

All good, I appreciate the feedback - I can reproduce this using the settings from the screenshot. I'm planning on a 1.3.7 release this week, so won't be far away.

N

**Comment by nathanwoulfe** [comment]
Knew it wouldn't be major - have fixed it, will be in tonight's nightly if you feel like verifying, otherwise will be in 1.3.7

**Comment by Chris-N1** [comment]
Excellent, thanks Nathan - I'm hoping Umbraco 8.6.4 will be out by next week, so I can push some of the fixes in that to Live at the same time as 1.3.7, but I'll grab this build and test it locally and in the Dev environment in the meantime :).

**Comment by nathanwoulfe** [comment]
Sounds like a plan - 1.3.7 beta is on NuGet now. Let me know how you go.

**Comment by Chris-N1** [comment]
Thanks Nathan - all seems good, have asked the client to do some testing :).
