### ISSUE TITLE
Plumber licenseing Issue

### ISSUE THREAD

**Issue by charlenevas21** [nathanwoulfe/Plumber-2#32]
![Capture](https://user-images.githubusercontent.com/39157448/87299513-0ef99480-c504-11ea-95d9-10fceaf641c2.PNG)

Hi Nathan,

I've upgraded plumber to the latest release (v1.3.6) and I'm getting this error. If i try to go to the licensing tab - it gives me a 404 error  - undefinedplans.

The license file is in the plumber folder but its still giving me this error.
![Capture](https://user-images.githubusercontent.com/39157448/87299751-84656500-c504-11ea-9996-e0c24d1971ff.PNG)

**Comment by nathanwoulfe** [comment]
Hi Charlie

Might be a caching issue - that modal doesn't exist in the latest codebase so should not be displayed.

You can delete the old license and key file too (unless it's a paid license, of course). Latest version doesn't require either (unless it's a paid license, of course).

**Comment by charlenevas21** [comment]
Hi Nathan,
Got it sorted.
I unistalled the plugin and then installed it again.
