### ISSUE TITLE
Window for comparing changes is a little to small

### ISSUE THREAD

**Issue by Sjoerdson** [nathanwoulfe/Plumber-2#33]
Hi Nathan,

Recently we installed your plugin for one of our clients and overall they are very satisfied! One thing thats a little inconvenient is the window where a reviewer can compare the changes (old vs new): The window that appears is a little too small, especially if the changes involve large texts (see image below). So, it would be more convenient if this window would be wider or if the user could make it wider instead of the need to scroll. A lot of scrolling doesn't make it easier to check what has actually been changed on a document.

Is this something you could possibly help us with? 

![image](https://user-images.githubusercontent.com/42436568/89505293-ac757a80-d7c9-11ea-97a2-2a748c8f6479.png)

Thanks in advance.
Sjoerdson

**Comment by nathanwoulfe** [comment]
Hi @Sjoerdson that's a good point, and easily changed. I'll include it in the next patch release. 

No ETA for that as yet, working through some performance improvements so want to take the time to get those right.

**Comment by nathanwoulfe** [comment]
@Sjoerdson this will be in the next nightly (will be on NuGet in 8 hours from the time of this comment). I've bumped it up to use the medium-width overlay, not sure why I ever thought small was appropriate...

**Comment by Sjoerdson** [comment]
@nathanwoulfe Thats perfect. Thanks for your dedication.

**Comment by lordscarlet** [comment]
How do I get to this dialog?

**Comment by nathanwoulfe** [comment]
@lordscarlet this is displayed in the workflow app, at the top of the change description card. It's a licensed feature so won't be available without either a legitimate license, or a test license on a non-prod domain

![image](https://user-images.githubusercontent.com/3248070/93154187-61467400-f746-11ea-8ac7-5bc8f545739e.png)

**Comment by lordscarlet** [comment]
@nathanwoulfe ah, that's why I don't see it. Not running on localhost and don't have a license yet.

**Comment by nathanwoulfe** [comment]
Not sure why I've locked that one - license should really only be managing the total number of groups and a couple of advanced features. Content diff is core feature and should be always on. I'll wind that back in 1.4.4
