### ISSUE TITLE
No content action

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#34]
Caveat: We have an unusual build process that complicates matters. I can explain if needed.

When I attempt to go to the actions for a node, I expect to see "Workflow" as an option, so that I can setup workflow for that node (and it's children). That is how I recall it working in Plumber v1. However, when I do so, I see no such action.

![image](https://user-images.githubusercontent.com/17951/89820191-a0b3ec00-db1a-11ea-9b02-eacf04562117.png)

I also do not see that as an available action when setting up an Umbraco user group.

![image](https://user-images.githubusercontent.com/17951/89820289-cc36d680-db1a-11ea-8777-8d850833d163.png)

Am I looking in the wrong place, or is there something wrong with my installation?

**Comment by lordscarlet** [comment]
Found it, I apologize. 

 
![image](https://user-images.githubusercontent.com/17951/89820539-2cc61380-db1b-11ea-8a3c-caf1d24d6ab3.png)

**Comment by nathanwoulfe** [comment]
All good @lordscarlet, v8 version is all about that content app 😄

**Comment by lordscarlet** [comment]
I may have other questions coming up, is issues the best place to put them? Some are unfamiliarity with the UI, some are how to either role my own enhancements via events or possible feature requests.

**Comment by nathanwoulfe** [comment]
Absolutely toss them in issues - good for visibility for others too. 

Happy to help wherever I can.
