### ISSUE TITLE
When I request approval and go to another page, umbraco asks me if I want to stay or discard changes, but the changes are already saved.

### ISSUE THREAD

**Issue by ThomasHerckenrath** [nathanwoulfe/Plumber-2#36]
Hi!

When I make some changes on a page and request approval, the current page will be saved and is put into a workflow, so it can be approved. If I go to another page after doing this, Umbraco asks me if I want to stay or discard the changes made to the page. Is it possible to not show this pop-up? It doesn't make sense in this case, because the changes to the page are already saved by submitting the workflow request, it doesn't make sense in this context. If I press discard, my changes stay available for approval. 

Do you maybe know how to do this?

**Comment by nathanwoulfe** [comment]
Hi @ThomasHerckenrath 

I thought I'd fixed that! Will double check in the latest code, and include it in 1.3.9 if it's still an issue. It stems from how the content form is managed when it's saved - when the save is triggered from the Plumber content app, it seems like the form state doesn't reset correctly... Good times.

**Comment by lordscarlet** [comment]
Anecdotally I have definitely seen this as well, but I haven't taken the time to reproduce and be sure when it happens.

**Comment by nathanwoulfe** [comment]
Was missing some magic - `this.$element.inheritedData('$formController').$setPristine();` gets the content form and sets the state back to pristine after saving.

Will be properly fixed in 1.3.9.

**Comment by nathanwoulfe** [comment]
Should be resolved here => [Plumber_1.3.9-beta-000416.zip](https://github.com/nathanwoulfe/Plumber-2/files/5144499/Plumber_1.3.9-beta-000416.zip)

Will fire off a proper release soon.

**Comment by nathanwoulfe** [comment]
This has been fixed as part of 1.3.9
