### ISSUE TITLE
404 is generated when a user "Requests Publish" on a newly created document without saving

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#38]
This isn't a big issue at all as most people probably save as they're going along anyway, but just for the sake of consistency :).

If a user creates a new document and then clicks "Request Publish" without saving the document first a 404 error bar is generated.

1. As a user with permission to create a document and request publish, create a new document
2. Click on "Request Publish" to go to the "Initiate Workflow" tab; do not click "Save" first.
3. Enter a comment and click "Request Publish"
4. A 404 error appears in a red bar at the bottom of the page

**Expected behavior**
For consistency I'd expect the new document to be saved automatically when "Request Publish" is clicked.

**Plumber version**
1.3.8

**Additional context**
If a user has already clicked "Save" then this issue doesn't occur so the publish request just needs to check whether the document being request is being published for the first time (not sure if that's practical, I guess it depends whether Plumber usually POSTs an ID).

**Comment by nathanwoulfe** [comment]
Thanks @Chris-N1, that's a bit of a strange one, I thought the workflow app wasn't displayed on new, unsaved nodes... That's the intention at least, workflow shouldn't be available at all until the node has been saved. 

Will fix it up for the next release, which is now feeling a bit overdue.

**Comment by nathanwoulfe** [comment]
@Chris-N1 this needs to work a little differently - it's not possible to allow submitting into the workflow without saving the page first, as there may not be workflow configured for the node. Given that depends on the node having an ID, the config can't be set until the node has been saved, so will need to be two steps - save, then configure workflow.

**Comment by nathanwoulfe** [comment]
Should be resolved in the beta => [Plumber_1.3.9-beta-000416.zip](https://github.com/nathanwoulfe/Plumber-2/files/5144501/Plumber_1.3.9-beta-000416.zip)

**Comment by Chris-N1** [comment]
Thanks Nathan - it was a bank holiday here yesterday so only just seen this. We're in the middle of testing Umbraco 8.6.4 with Plumber 1.3.8 but we'll upgrade to 1.3.9 as soon as it's released - I'll test this separately in the meantime 👍
