### ISSUE TITLE
Ability to unpublish with no approval

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#40]
It would be nice to allow users to unpublish nodes without requesting approval.

It would be even better to be able to set this per document type or node (depending on preference)

Our client only requires approval for publishing content items.

**Comment by nathanwoulfe** [comment]
Hi @AaronSadlerUK, this now has me thinking - would be cool to be able to assign a different workflow for publish and unpublish, so a given node may have a publish workflow but no unpublish, or unpublish but no publish, or different options for both...

Code already identifies publish vs unpublish workflow, so would be an additional db column to tag a workflow step as publish or unpublish, then modifying some queries to get the correct steps. Will see what I can make work.

**Comment by nathanwoulfe** [comment]
v1.4.0 adds a global option to enable/disable unpublish workflows, plus node/content type option to do the same - user can disable unpublish for the whole site, or per node/content type
