### ISSUE TITLE
Possible to publish on Info tab

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#41]
It is possible to Save and Publish a node by clicking the content tab, bypassing the workflow entirely.

To do this I created a test user with editor permissions and click on the info tab, this reveals the save and publish button

**Comment by nathanwoulfe** [comment]
Hi @AaronSadlerUK, I'm pretty sure this is resolved in the next release - I use signalr to broadcast some state changes, but it doesn't always seem to work. Have revisited it as part of other changes. 

Will confirm and let you know

**Comment by AaronSadlerUK** [comment]
Ok cool, screenshots below just as reference:

![image](https://user-images.githubusercontent.com/9937803/94191741-e435a000-fea5-11ea-991f-bc483222f032.png)

Info tab:
![image](https://user-images.githubusercontent.com/9937803/94191778-f44d7f80-fea5-11ea-9e0c-64746b19fadf.png)

**Comment by AaronSadlerUK** [comment]
@nathanwoulfe Any updates on this?
It's a blocker for the client to go live, as you can appreciate having paid 900EUR they are being pushy

**Comment by nathanwoulfe** [comment]
It looks to be all good in latest (1.4.0) - I'd like to get that out this week, but the nighty is available and solid. 

Will try to get some time on it tomorrow

**Comment by AaronSadlerUK** [comment]
This seems to work perfectly on 000432

**Comment by nathanwoulfe** [comment]
Annnnd released in 1.4.0
