### ISSUE TITLE
Unable to create new content item

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#44]
I am unable to create any new content items regardless of their workflow configuration.

This on the latest v1.4.0 version.

All I get is a 404 error when clicking the request publish button.

It is possible to update an existing content item however.

This happens in both Explicit and & Implicit modes:

![image](https://user-images.githubusercontent.com/9937803/95182864-122bb600-07bd-11eb-96c7-dadb9c03331b.png)

**Comment by nathanwoulfe** [comment]
I have a feeling that is due to the new node not having an id when calling the save endpoint. 

Probably should be hiding the workflow app until the node has been saved, which would prevent this from ever being possible...

**Comment by AaronSadlerUK** [comment]
A new node would still need this to log why it was created in the first place surely?

**Comment by nathanwoulfe** [comment]
Would still be workflowed for publishing, but not for the initial save of the new node. I'll have a look at why it's happening, this would be the last resort

**Comment by AaronSadlerUK** [comment]
Ah ok that makes sense 👍

**Comment by AaronSadlerUK** [comment]
@nathanwoulfe Many thanks for your quick work!

I can confirm this is no longer an issue in v1.4.1-beta-000455

**Comment by nathanwoulfe** [comment]
Fixed in 1.4.1 🚀
