### ISSUE TITLE
Console error - signalr 403

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#45]
When logged in as an editor which is in an approval group, when you click request publish signalr returns a 403 error:

![image](https://user-images.githubusercontent.com/9937803/95183454-e957f080-07bd-11eb-9ffd-1e0710e17120.png)

**Comment by AaronSadlerUK** [comment]
I can confirm this is no longer an issue in 1.4.1-beta-000455

**Comment by nathanwoulfe** [comment]
Fixed in 1.4.1 🚀
