### ISSUE TITLE
Console error when approving

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#46]
When a user logged in as an editor clicks approve after requesting publish there is an error logged in the console:

![image](https://user-images.githubusercontent.com/9937803/95183706-40f65c00-07be-11eb-81ff-2e757d6823f9.png)

**Comment by nathanwoulfe** [comment]
I noticed that earlier, ignored it because I was on latest Umbraco source and figured it was unrelated to Plumber. Possibly caused by show/hide logic on the footer buttons

**Comment by AaronSadlerUK** [comment]
Possibly, This site is running on 8.6.5

**Comment by AaronSadlerUK** [comment]
I can confirm this is no longer an issue in v1.4.1-beta-000455

**Comment by nathanwoulfe** [comment]
Fixed in 1.4.1 🚀
