### ISSUE TITLE
Preview button on details window

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/Plumber-2#47]
My client has requested would it be possible to add the preview button onto the details window, so that they can see the changes visually.

See my screenshot below:

![image](https://user-images.githubusercontent.com/9937803/95329702-4d061a80-089f-11eb-8bca-eb3aa84b137a.png)

**Comment by nathanwoulfe** [comment]
Hi @AaronSadlerUK, I see no reason why not - might need to consider how that works alongside the inline diff button on the change description card, both buttons should really be co-located. 

Absolutely do-able though.

**Comment by nathanwoulfe** [comment]
I've included this in 1.4.1, which is available now - a useful addition, thanks for the suggestion.

**Comment by lordscarlet** [comment]
> Hi @AaronSadlerUK, I see no reason why not - might need to consider how that works alongside **the inline diff button on the change description card**, both buttons should really be co-located.
 
I feel like I have asked this somewhere else, but I haven't been able to find it if so. Where is the diff button? I dont' see it in my UI.

![image](https://user-images.githubusercontent.com/17951/104650163-c6be5900-5683-11eb-9f73-8931f2fd4499.png)

**Comment by lordscarlet** [comment]
Found it, I need our license to be purchased before it will be available. https://github.com/nathanwoulfe/Plumber-2/issues/33#issuecomment-692405218
