### ISSUE TITLE
Selecting an action on initiate workflow page does not update action

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#49]
**Describe the bug**
If you use the dropdown button on the initiate workflow page it does not change the submitted action.

**To Reproduce**
1. Click on the "Request Publish" or "Request unpublish" button on a page
2. On the "initiate workflow" page, select some other action
3. Log off and then Log on as a user who can see the publish request
4. The request will have been submitted as whatever was chosen from the first button, not the update you made on the initiate workflow page.

**Expected behavior**
Either the dropdown options should be hidden on the initiate workflow page or the action selected on this page should be the one submitted.

**Screenshots**
1. - Request Publish
![image](https://user-images.githubusercontent.com/46811766/97153879-179c7080-176b-11eb-8003-e329ad9643d7.png)

2.: Switch to Request Unpublish:
![image](https://user-images.githubusercontent.com/46811766/97154333-a8734c00-176b-11eb-9087-1c7d31d61b93.png)

3. Request is submitted as a publish rather than Unpublish
![image](https://user-images.githubusercontent.com/46811766/97154441-ca6cce80-176b-11eb-8ab4-1e33b7ef14b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (64-bit)

**Plumber version**
1.4.2

**Additional context**
Not a biggie, just something you might want to fix :).

**Comment by nathanwoulfe** [comment]
Thanks @Chris-N1, this is fixed in 1.4.3-beta, on NuGet now if you feel like verifying 😄

**Comment by Chris-N1** [comment]
Thanks Nathan - I'll take a look at that today 👍

**Comment by Chris-N1** [comment]
Sorry, that took a while to test (other clients getting in the way) but this is fixed in the latest version :)

**Comment by Chris-N1** [comment]
Not sure if you want me to raise a new issue for this but now if I try to "publish" a change the actual request goes through as an "unpublish":

Publish request:

![image](https://user-images.githubusercontent.com/46811766/98365541-7ba41c00-202a-11eb-81c7-d8c34e9cae1a.png)

Result:
![image](https://user-images.githubusercontent.com/46811766/98365640-9d9d9e80-202a-11eb-84ff-e7600c7fe578.png)

Workflow history page:
![image](https://user-images.githubusercontent.com/46811766/98365710-b5752280-202a-11eb-9d3f-e52244baded5.png)

**Comment by nathanwoulfe** [comment]
@Chris-N1 good catch - that will only be happening when the node has unsaved changes, because I'm not passing the correct parameter back into the initiate function after saving. Will be fixed in the next nightly/1.4.3
