### ISSUE TITLE
System.InvalidOperationException error

### ISSUE THREAD

**Issue by DegsyD** [nathanwoulfe/Plumber-2#51]
**Describe the bug**
System.InvalidOperationException: Sequence contains more than one element error after clicking Offsite Approval link.

**To Reproduce**
1. Go to Content
2. Make a change
3. Click Request Publish
4. Receive Offline approval email
5. Click on Offsite Approval link
6. See Error

**Expected behavior**
The page to be previewed with the proposed content changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/17767149/97429651-a3e79880-190f-11eb-929b-d63338baceea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.106 (Official Build) (64-bit)
- Umbraco version 8.4.0

**Plumber version**
1.4.2

**Additional context**
Was also happening on 1.3.9, on localhost as well as QA environment.

**Comment by nathanwoulfe** [comment]
Hey @DegsyD, pretty sure I know what's happening here - the GetNewestTaskByNodeId method expects to find a single workflow task for the given node id, but that doesn't consider variant nodes which can have multiple active workflows. Will investigate and include a fix in 1.4.3.

**Comment by nathanwoulfe** [comment]
Plumber.Workflow.1.4.3-beta-000470 will be on NuGet soon, it should resolve this issue - please let me know

**Comment by DegsyD** [comment]
Seems to work on localhost, although on the environments we aren't seeing anything in the workflow tab, and we suspect it's caused by the following error:
![error](https://user-images.githubusercontent.com/17767149/97562592-c514bb80-19d9-11eb-9459-730126905c65.png)

Although I suspect it's possibly an issue on our end.

**Comment by nathanwoulfe** [comment]
I'll see if I can reproduce. Possibly caching on other environments (app_plugins is held fairly aggressively). 

`excluded` is a property on `config`, which always exists (as an empty or populated NodeConfigViewModel object), so I'm thinking it's most likely a cache/client dependency thing after upgrading. Try bumping the client dependency version in /config/ClientDependency.config...

**Comment by DegsyD** [comment]
We got this working after upgrading to 1.4.3-beta-000471, although we appear to be having issues with scheduled posts going live instantly on approval. As it's not linked to this I think I'll create a separate thread.

**Comment by nathanwoulfe** [comment]
Thanks @DegsyD - I'll probably get 1.4.3 out this week, hopefully that can include any fixes required for scheduled publishes (if needed)

**Comment by nathanwoulfe** [comment]
Closing this as 1.4.3 will be out in a day or two
