### ISSUE TITLE
Scheduled Content going live on approve.

### ISSUE THREAD

**Issue by DegsyD** [nathanwoulfe/Plumber-2#53]
**Describe the bug**
When content is submitted for approval with a scheduled date/time, on approval the content goes live immediately before the date/time has passed.

**To Reproduce**
1. Go to 'Request Publish'
2. Describe changes 'Describe the change'
3. Click on 'Set Date'
4. Enter date/time in future
5. On approval changes go live instantly, rather than at the requested published time.
**Expected behavior**
On approval changes should go live at the requested published time.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Plumber version**
1.4.2

**Comment by nathanwoulfe** [comment]
@DegsyD I've been trying to reproduce this, with no success. What I have noticed though is the preview cookie sometimes hangs around, which means viewing the content after completing the workflow shows the preview version, which would have the scheduled changes.

Could you check that this isn't cookie-related? I've submitted 10+ workflows just now, all work fine when scheduling...

**Comment by DegsyD** [comment]
I cleared the cookies and now I'm having the opposite problem, content isn't publishing now, is there anything else on our end we might need to check?

**Comment by nathanwoulfe** [comment]
I'd clear all cookies, log out, clear browser cache etc to get back to a clean slate. Check that the Umbraco publish and preview are behaving as expected. Then try a non-scheduled workflow, then a scheduled one. Clearing the cookie won't stop content from publishing.

I'm not seeing any issues in my testing.

**Comment by NikRimington** [comment]
Note: We've had a client reporting this behaviour. Haven't yet investigated, but once I do will add more info to this issue if able to replicate reliably.

**Comment by nathanwoulfe** [comment]
Thanks @NikRimington, would be good to see some steps to reproduce - per my comment above, it's working fine in my tests. That said, my tests will be me using it the way I expect the feature to work, so may not be a real-world test case...

**Comment by DegsyD** [comment]
@nathanwoulfe I haven't had much chance to look at this lately until today, but realised I could have added more detail in the initial issue, the steps I took today are:
1. Make a change to an existing page.
2. Click 'Save'
3. Click 'Request Publish'
4. Type description of change into 'Describe the changes'
5. Ignore Attachment Field
6. Click 'Scheduled Date'
7. Select today's date on calendar picker with time of 15 mins into future for test.
8. Click 'Request Publish' in workflow tab.
9. Click 'Approve' in workflow tab as I have Flow Type set to Explicit.

Then after the scheduled time the content had not published. Approving a publish request without a schedule applies the change instantly.

**Comment by Chris-N1** [comment]
@DegsyD are you using Umbraco 8.6.5? 

I ask because I've just had a report that the underlying Umbraco functionality for scheduled publishing (which I assume Plumber uses under the covers) isn't working and I've just tried it myself as an admin and replicated the issue on our Dev server (without using Plumber's workflow at all).

**Comment by DegsyD** [comment]
@Chris-N1 We're using Umbraco 8.4.0 at the moment. But I'll check to see if Umbraco's schedule is working for me on that version without Plumber Workflow.

**Comment by DegsyD** [comment]
@Chris-N1 Our Umbraco schedule works, however I have noticed that when I schedule a publish with the workflow, the info tab in Umbraco does not get the "Publish At" field below the "Created Date".

**Comment by nathanwoulfe** [comment]
@DegsyD looking at this now - following your repro steps, scheduling works fine (umb 8.8, plumber 1.4.3) - after completing the workflow, no changes are published. Once the scheduled time passes, changes go live. Wondering if it's a combination of 8.4 and something in my scheduling logic not getting along... Scheduling was added in 1.2.0, which aligned with 8.4, but I shifted to 8.5 fairly soon after, so there may be issues with 8.4.

The Publish At field will update if you refresh the node. Plumber sets the scheduled date server-side as part of initiating the new workflow, so the bound node in the backoffice isn't aware of the change. Looking at how that works, it's actually bit clunky - I'll see if I can reuse Umbraco's scheduling UI in the backoffice and remove some of my custom stuff.

**Comment by nathanwoulfe** [comment]
@DegsyD I've revisited how the scheduling works, so the UI now updates in sync with creating/cancelling/approving workflows - it's now scheduling content using the same mechanism as Umbraco (calling into contentResource.saveSchedule), so should be fine. I've checked it locally, works perfectly - workflow is completed, then changes are published once the release date passes.

It's in the latest nightly, which will be available in around 2 hours from the time of this comment.

**Comment by DegsyD** [comment]
@nathanwoulfe Tested this morning locally and it is behaving as expected on 1.4.4-beta-000491

**Comment by nathanwoulfe** [comment]
@DegsyD glad to hear. I'm still not sure why it wasn't working properly previously (excluding the UI update, fully aware of what was happening there). All good though, I'm aiming for a pre-Christmas release with some other changes, but depending on my motivation levels that may well be pre-New Year...
