### ISSUE TITLE
Missing "Save and Publish" buttons for admins/workflow group users

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#54]
**Describe the bug**
It appears that admins and workflow group users with permission to Publish can no longer bypass workflow (as of 1.4.2)

**To Reproduce**
Log on as an admin or a user with the "Publish" right set in Umbraco. On attempting to publish a page you cannot see the "Save and Publish" button (logged on here as a Super Admin - I can still un-publish or publish the document with descendants, or schedule a publish which will occur without approval):

![image](https://user-images.githubusercontent.com/46811766/98365991-2caab680-202b-11eb-8c50-3f92c9a96c01.png)

**Expected behavior**
I expect to be able to bypass workflow as an admin or member of a workflow group with publish rights.

**Desktop (please complete the following information):**
 - OS: Windows 10/iOS
 - Browser: Chrome, Safari, Edge, Firefox

**Plumber version**
1.4.2, also occurring in latest build of 1.4.3

Edit - just to make sure I tried this on a totally fresh install using Umbraco 8.6.4 with Plumber 1.4.2; with 1.3.8 it was fine, with 1.4.2 the problems occurred.

**Comment by nathanwoulfe** [comment]
@Chris-N1 yup, my mistake here - missed updating a variable when changing how buttons were assigned. Will be in the next nightly, and fixed in 1.4.3

**Comment by Chris-N1** [comment]
Thanks @nathanwoulfe - I can confirm that has fixed it 👍

**Comment by nathanwoulfe** [comment]
@Chris-N1, magic, glad to hear it. Will get 1.4.3 out before the end of the week

**Comment by lordscarlet** [comment]
I'm glad I came here before pulling my hair out, running into the same problem. Upgrade it is!
