### ISSUE TITLE
License file not working

### ISSUE THREAD

**Issue by jesperweber** [nathanwoulfe/Plumber-2#57]
**Describe the bug**
Bought a license as we need some of the pro features. But after adding the license, Plumber still runs in trail mode.

**To Reproduce**
1. Added the plumber.lic file in the /App_Plugins/plumber folder
![image](https://user-images.githubusercontent.com/2575817/99521114-45ed2480-2994-11eb-8645-03ec3ec4a78c.png)

2. Restarted the website
3. Liense is still on trail
![image](https://user-images.githubusercontent.com/2575817/99521752-168ae780-2995-11eb-818f-90b076ce79cb.png)

**Plumber version**
1.4.2

**Additional context**
I also tried to enter the license and key and click Validate on the licensing page, but Plumber still runs on trail license.

Note: The site runs on a sub-domain for the registered domain in the license file.

**Comment by nathanwoulfe** [comment]
Hi @jesperweber, I'll look into this first thing in the morning (1am here now).

**Comment by nathanwoulfe** [comment]
@jesperweber I've tried your license on my local env, it validates without issue. Also checked the tests, a subdomain of the licensed domain generates a valid license.

 So, we'll need to check some things:
- anything in logs? Looking for messages from Plumber.Core.Licensing
- Umbraco version? I'll do a clean install of 1.4.2 on your Umbraco version, and see if I can reproduce
- Is the backoffice on a server where ServerRole is Replica? 
- does the license validate correctly in a dev environment?
- is the key or license file empty?
- is there any deployment/CD pipeline, or are you adding the license directly on the production site?

**Comment by jesperweber** [comment]
Ok, it's working now, maybe I was not able to copy/paste the right key yesterday :-)

Just to be clear. It's not enough to just past the license file in the /App_Plugins/plumber folder and restart the site, you need to enter the license informations and click validate?

For now i have just placed the file on the site manually, but for normal deployments we have a Azure DevOps pipeline doing the deployment, so hopefully this will still work after a deployment.

**Comment by nathanwoulfe** [comment]
Hi @jesperweber glad to hear it's working (and thanks for your support)

Having the key and license files will be enough - if those are on the filesystem when the site boots, they'll be loaded and validated. Doing it from the backoffice updates the files and triggers an application restart, so effectively does the same thing. Long story short, if the files are in source control, should be fine.

**Comment by jesperweber** [comment]
Cool, we have both the licens and key file as part of the deploy, so it should be fine.

Thanks @nathanwoulfe
