### ISSUE TITLE
Ability to filter Workflow History

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#58]
At the minute the Workflow History section is a paged list of items, however there is no way to filter the results or search the results. It would be great if it was possible to filter by "Type", "Status", "Requested by" and a "date range for Requested on".

![image](https://user-images.githubusercontent.com/13313745/99686625-af942e00-2a7b-11eb-950a-46b8779d5517.png)

This would make it easier to find information in this view.

**Comment by nathanwoulfe** [comment]
@NikRimington agree 100% - would be super useful. There is a filter for status, but it's only exposed in the UI via the cards in the chart header on the workflow section dashboard.

I'd planned on improving the chart (adding some new datapoints etc) in the next release, would make sense to include this too, and focus the release on reporting/insights

**Comment by nathanwoulfe** [comment]
@NikRimington next release will include history filters - it's in the next nightly, which arrives on nuget in about 2 hours from now.
Aiming to release it tomorrow if I can find a few minutes for final testing.

![image](https://user-images.githubusercontent.com/3248070/102964503-92012b00-4537-11eb-9826-f66a93ab72f1.png)

**Comment by nathanwoulfe** [comment]
Included in 1.5.0
