### ISSUE TITLE
Adding content type flow

### ISSUE THREAD

**Issue by jenluong-deepend** [nathanwoulfe/Plumber-2#6]
**Versions** 
Fresh install of Umbraco: 8.3.0 & Plumber: 1.0.4

**Issue**
Unable to create content type flows. I can go through and setup the "current flow", but get this error once I press "save". Not sure if part of my problem is that I'm using the incorrect license file? Using the one here: https://github.com/nathanwoulfe/Plumber-2/releases/tag/v1.0.0-beta 

----

Exception Details
InvalidLicenseException: Error saving content type config: {message}
Stacktrace
```
at Plumber.Core.Licensing.LicensedFeature(String[] levels)
   at Plumber.Core.Services.Implement.ConfigService.UpdateContentTypeConfig(ConfigModel model)
   at Plumber.Web.Api.ConfigController.SaveContentTypeConfig(ConfigModel model)
```

---

Side note, I would like to say thank you for all the work that was done for the Umbraco 7 Plumber  the plugin was really helpful! We would also like to use it in Umbraco 8 as well (and will be needing it quite soon). Appreciate the effort you have done so far to put Umbraco 8 version together!

**Comment by nathanwoulfe** [comment]
I'm surprised that license actually works at all, I've made some substantial changes to how licenses are validated since that beta was published... Content type flows are now a licensed feature, so require the basic license at minimum. 

Appreciate the kind words too! 😁

**Comment by jenluong-deepend** [comment]
@nathanwoulfe hahah oh right! What should I be doing now for licensing (sorry if this is mentioned somewhere already)? Should I try and go through the subscription section and try setup a trial license with the test stripe payment details?

**Comment by nathanwoulfe** [comment]
I'll need to generate a couple of new licenses, will attach them to the release (which also needs to be updated with the latest)
