### ISSUE TITLE
User Guide/Wiki

### ISSUE THREAD

**Issue by mixedup4x4** [nathanwoulfe/Plumber-2#61]
Is there a user guide or a set of documents that are a little more "in depth" for people to use?  We are new to Umbraco and thus, new to Plumber(-2) - we have purchased the paid license

**Comment by nathanwoulfe** [comment]
Hi @mixedup4x4 there's not anything more detailed at the moment, but there really should be. It's a time thing (or lack there-of)

Are there particular pain-points which would warrant more explanation? More than happy to offer guidance where I can.

Writing quality docs is hard - I'm so close to the product that it all seems obvious 😃

**Comment by mixedup4x4** [comment]
I'll get some input from our devs/users and reach back :)

**Comment by nathanwoulfe** [comment]
Awesome, would be good to know where the pain points are.

**Comment by maulik-modi** [comment]
@mixedup4x4 or @nathanwoulfe , Has there been any progress on Userguide or Usermanual. We are bidding a contract and want to recommend this provided it has good documentation/user manual for end user training.

**Comment by mixedup4x4** [comment]
@nathanwoulfe, sorry it's been a while, my dev/qa team are kinda like most of us....'stubborn and hard headed'....they've almost got it all sorted out....BUT, I have kept telling them, that reaching back with anything is how open source works ... so here's hoping :)

**Comment by nathanwoulfe** [comment]
https://our.umbraco.com/documentation/Add-ons/Umbraco-Plumber/
