### ISSUE TITLE
Question: Plumber 2 license

### ISSUE THREAD

**Issue by SRandomName** [nathanwoulfe/Plumber-2#63]
Hello !

We have a question about plumber 2 license costs.
I read that the paid license is a one-off, €900 one-time payment. 
Does this mean we can use this license on several projects/domains ?
Or do we have to pay €900 to use this package on each domain?

In case we need to pay for each domain: 
We have 3 environments running on umbraco cloud with each 4 different domains. Does that mean we need to pay for each environment once ? Or €900 x 4 different domains?
Thnx !

**Comment by nathanwoulfe** [comment]
Hello @SRandomName 

The license is per-domain, but that covers all sub-domains too, so if your setup was domain.com for production, with edit.domain.com as the backoffice server, licensing domain.com will cover everything. 

With your cloud setup, is it a single backoffice instance? The license would need to cover whatever domain hosts the backoffice - if there are multiple front-end domains, that won't (shouldn't) matter. If you could give some more detail about your setup, I should be able to give more confident advice.

**Comment by SRandomName** [comment]
We use umbraco cloud with 3 environments (dev - staging - live). We might want to use plumber 2 on staging and live environment.
Live environment has 4 different domains for each language. For example:
www.example.com
www.example.be
www.example.fr
www.example.de

Staging environment is just using the umbraco cloud domain with one-level paths:
clouddomain/en-us
clouddomain/be
clouddomain/fr
clouddomain/de

Dev environment is using the same setup as staging environment. But we haven't decided yet if plumber 2 should be active there aswell.

**Comment by nathanwoulfe** [comment]
Ok, that should be fine - you'd need to license the staging domain only, because the license only cares about the backoffice environment, of which you'll have one. 

Probably not needed on dev, I'm assuming you're not editing content on dev?

**Comment by SRandomName** [comment]
And what about the live environment ? 
4 licenses for each front-end domain + 1 for the backoffice domain ?

**Comment by nathanwoulfe** [comment]
Where is the editing happening? I'd assumed it would be on the single staging server? If the live servers are front end only (ie no backoffice) they don't need to be licensed.

**Comment by SRandomName** [comment]
Editing will happen in staging and live. So 2 licenses for each backoffice domain will be enough. Thanks !

**Comment by nathanwoulfe** [comment]
I'd need to confirm, there might be a more efficient way to make this work - are the live environments sharing a single Umbraco instance? Might be able to generate a single license for the different domains to save you purchasing multiple

**Comment by SRandomName** [comment]
Yes, the live environment with 4 front-end domains is sharing a single umbraco instance ( 1 backoffice domain).

**Comment by nathanwoulfe** [comment]
So all editing happens on the same domain, even if it's come from a different front end server? 

It's been a long week, just trying to get it straight in my head 🙄

**Comment by SRandomName** [comment]
No, staging has a different domain then live environment backoffice :-D 
Staging example backoffice url: https://stage-www-cloudenvironment.umbraco.io/
Live example backoffice url: https://www-cloudenvironment.umbraco.io/

**Comment by nathanwoulfe** [comment]
Hmmm. You'll need a license for any domain where content is edited, but if there is a common root domain (with subdomains for edit/stage etc), licensing the top level domain would be enough. 

If live and stage are two different backoffice instances, both would need licenses. I'll double check in the morning if there's any alternate ways I could set it up

**Comment by SRandomName** [comment]
Ok, thank you !

**Comment by nathanwoulfe** [comment]
@SRandomName I'm still not sure I'm entirely across your setup (happy to take this to email if it means you can share more detail).

However...

If you have https://stage-www-yourdomain.umbraco.io and https://www-yourdomain.umbraco.io these should both be covered by a single license, provided you register the license for www-yourdomain.umbraco.io. I've added both as test cases in my unit tests, and they pass, so should be all good.

**Comment by SRandomName** [comment]
1 license for live environment (with 4 domains for front-end & 1 for backoffice) IF it's the same setup that you're describing.

If you want i'll send you an email with more details.

**Comment by nathanwoulfe** [comment]
Might be a good idea - nathan @ nathanw.com.au
