### ISSUE TITLE
Add "Attachment" label to language file

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#65]
Can you add the "Attachment" label to the language file. I don't actually need to do a translation, but I want the attachment to be used for a specific purpose and I would like to change the label based on that. It probably makes sense to do "Add File" as well.

![image](https://user-images.githubusercontent.com/17951/104649330-91fdd200-5682-11eb-8b66-7274d97a457c.png)

**Comment by nathanwoulfe** [comment]
@lordscarlet absolutely - I thought I'd caught all the locale strings. Obvs not.

Will include in 1.4.4.

**Comment by nathanwoulfe** [comment]
1.4.4 became 1.5.0, which includes this change.
