### ISSUE TITLE
Error getting version information

### ISSUE THREAD

**Issue by SRandomName** [nathanwoulfe/Plumber-2#68]
After adding the license key we get this error: 
![image](https://user-images.githubusercontent.com/48089189/105860478-ea6f9080-5fed-11eb-942c-5d202c6d6d08.png)

Versions:
Plumber - v1.4.4-beta-000487
Umbraco - v8.8.2
Forms - v8.5.3
Deploy - v3.5.3

**Licensed version?**
Yes 

We mailed with you about licensing our 3 environments: Dev - Staging - Live.
Live is working as expected, but using the same license for staging environment brought up this issue.

**Comment by nathanwoulfe** [comment]
Hi @SRandomName, this won't be related to the license - first thing I'd do is update to the latest nightly (1.5.1), but that shouldn't impact this issue either. The URL requested in that method is public, so should never have a 403 response.

Does the workflow documentation load correctly (workflow section, link in left nav)? This also queries the GitHub API for data, so should behave similarly.

**Comment by SRandomName** [comment]
Yes the workflow documentation loads correctly. Looking at the backoffice workflow section today we don't get the error anymore while we didn't change anything.
