### ISSUE TITLE
Able to Request unpublish on unpublished item

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#72]
**Describe the bug**
If a node is currently not published, you are still presented with the option to unpublish it

**To Reproduce**
1. Go to a content node that is not published
2. Click on the carat next to "Request publish..."
3. You will see "Request unpublish"

**Expected behavior**
If a node is not published, there should not be an option to request unpublish

**Screenshots**
![image](https://user-images.githubusercontent.com/17951/107526857-4574bc00-6b86-11eb-8325-4af95da8024e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88

**Plumber version**
v1.5.1.509

**Licensed version?**
Not yet :(

**Comment by nathanwoulfe** [comment]
@lordscarlet that makes sense - change will be in tonight's nightly 👍

**Comment by nathanwoulfe** [comment]
@lordscarlet because I forgot to bump the version number, tonight's nightly is 1.5.1-beta-000520. Will be back to 1.5.2 tomorrow.

**Comment by nathanwoulfe** [comment]
Resolved in 1.6.0
