### ISSUE TITLE
New node approval flow

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#78]
**Describe the solution you'd like**
Allow the creation of an approval flow specific to when someone would like to publish a never-before-published node. Presumably, this would follow rules similar to the Document type approval flow as it concerns existing flow inheritance.

**Describe alternatives you've considered**
I thought about an action-based flow, but that seems complicated to implement, as what matters is when a publish or unpublish of the change takes place, not when the action takes place.

**Licensed version?**
Yes

**Comment by nathanwoulfe** [comment]
Hey @lordscarlet, I like the sound of this, and even better shouldn't be too much effort to implement. 

I think I'd approach it as a global setting, with a feature flag - admin can configure the new-node workflow to apply to all new nodes, but then also be able to turn it on/off. Then over on the workflow content app, it can show a UI alert of some sort to clarify that the new node will use a different approval flow to any configured on the node. 

I'm close to finalising a 1.6 release which adds razor views for emails and a few other bits, so once that's off the workbench, I reckon I can pull this in for the next feature release.

**Comment by lordscarlet** [comment]
Sounds excellent! Let me know if there is anything you could use from me.

**Comment by nathanwoulfe** [comment]
@lordscarlet this is now a thing in v2
