### ISSUE TITLE
Can only see oldest 5 tasks requiring my approval

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#79]
**Describe the bug**
When navigating to the Workflow dashboard under Content, I only see the oldest 5 tasks requiring my approval

**To Reproduce**
1. Place more than 5 items into a pending or rejected state
2. Navigate to `/umbraco/#/content`, and click the "Workflow" Dashboard

**Expected behavior**
I would expect to have access to all of the tasks pending my approval. Whether all are listed or there is some sort-of paging

**Screenshots**

Tasks requiring my approval:

<img width="1857" alt="tasks requiring my approval" src="https://user-images.githubusercontent.com/17951/112671136-309f6f80-8e38-11eb-9ef1-1d3f18f6095a.png">

Pending:

![image](https://user-images.githubusercontent.com/17951/112671223-4dd43e00-8e38-11eb-972e-d00d979f6ec2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19042.868
 - Browser: Chrome
 - Version 89.0.4389.90

**Plumber version**
 v1.5.1.509

**Licensed version?**
Yes

**Comment by nathanwoulfe** [comment]
@lordscarlet had a bug in the paging on the editor dashboard, resolved in tonight's nightly.

Will release either as 1.5.3, or roll it all into 1.6, depending on my availability.

**Comment by nathanwoulfe** [comment]
Fixed in 1.5.3
