### ISSUE TITLE
Long change description causes horizontal scroll or clipped text

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#83]
**Describe the bug**
If a long change description is entered, it creates a horizontal scroll or clipped text

**To Reproduce**
1. Request publish of a node
2. Enter a change description of moderate length (per #82, you can't make it particularly long)
3. View the Active workflow information and it will create a horizontal scroll
4. Go to the workflow dashboard or workflow history, and the text will be clipped

**Expected behavior**
I would expect the text to wrap gracefully based on the visible area.

**Screenshots**
![image](https://user-images.githubusercontent.com/17951/112681356-fab4b800-8e44-11eb-9e68-c459ebada7b9.png)
![image](https://user-images.githubusercontent.com/17951/112681376-01432f80-8e45-11eb-9dc7-0365eb280a02.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 89

**Plumber version**
v1.5.1.509

**Licensed version?**
Yes

**Additional context**
In lieu of another issue, I am also not getting line breaks where line breaks are entered

![image](https://user-images.githubusercontent.com/17951/112681545-47988e80-8e45-11eb-924f-8b3805d9b525.png)

**Comment by nathanwoulfe** [comment]
@lordscarlet same story here - in tonight's nightly, released in 1.5.3/1.6. Haven't addressed line break.

**Comment by nathanwoulfe** [comment]
Fixed in 1.5.3
