### ISSUE TITLE
View differences error

### ISSUE THREAD

**Issue by ja0b** [nathanwoulfe/Plumber-2#84]
**Describe the bug**
The package shows a non friendly error when you click on the "view differences" icon.

```
Received an error from the server
An error occurred
Error getting changes for workflow instance 44b0fb3c-8138-449c-b434-f1b662ee764e: Current license does not include this feature

Exception Details
InvalidLicenseException: Error getting changes for workflow instance 44b0fb3c-8138-449c-b434-f1b662ee764e: Current license does not include this feature
Stacktrace
at Plumber.Core.Licensing.LicensedFeature() in D:\a\1\s\Plumber.Core\Licensing.cs:line 24
   at Plumber.Core.Services.Implement.InstancesService.GetDiff(Guid guid) in D:\a\1\s\Plumber.Core\Services\Implement\InstancesService.cs:line 412
   at Plumber.Web.Api.InstancesController.GetDiff(Guid guid) in D:\a\1\s\Plumber.Web\Api\InstancesController.cs:line 145
```

**To Reproduce**
1. Go to workflow history or active workflow
2. Click on the "view differences" icon
3. See error

**Expected behavior**
See the license restriction in the slide view "View differences: ###" that appears when you click the button. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11311685/118062205-170ca580-b35c-11eb-9272-d605de2cd466.png)

**Desktop (please complete the following information):**
 - Browser: Brave Version 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)

**Plumber version**
 - Version: Plumber v1.5.3.541

**Licensed version?**
No, just playing with it first 🙂

**Additional context**
Just one extra question, is the plumber "view difference" using the same experience Umbraco to view differences ? (I hope not 🙄)

**Comment by nathanwoulfe** [comment]
@ja0b thanks for letting me know - that button shouldn't be visible at all on non-licensed installs, hence the error... Will fix it up.

And yeah, sadly it's the same diffing as the Umbraco core one. It's not great, but I'm not really sure what would be better, since more and more properties store JSON values, so it's not a very attractive visual compare...

Aiming for a v1.6.0 release soon (famous last words), will include this fix.

**Comment by ja0b** [comment]
@nathanwoulfe Awesome 👍!!! Thanks.
Regarding the diff thing... yes I know the default one is mehh that's why I was hoping this to be different 😅.
