### ISSUE TITLE
UmbracoCMS 8.12.2 does not start after Plumber 2 (v1.6) installed

### ISSUE THREAD

**Issue by mamray** [nathanwoulfe/Plumber-2#85]
**Describe the bug**
Umbraco CMS instance website unable to start after Plumber 2 (v1.6) is installed.

**To Reproduce**
1. Search for the nuget package Plumber.Workflow
2. Install it to the web application (single project in solution)
3. Put test.lic into required folder
4. Start application from VS2019 using IISExpress, see error.

**Expected behavior**
Application should start

**Screenshots**
https://prnt.sc/132z4cn

**Desktop (please complete the following information):**
 - Windows 10 Home
 - Google Chrome (Version 90.0.4430.93)
 - UmbracoCMS.Core version 8.12.2

**Plumber version**
Plumber.Workflow version 1.6.0

**Licensed version?**
Test license, checking ability to use before buying it.

**Comment by nathanwoulfe** [comment]
Hi @mamray, that's a bit annoying... There must be some dodgy SQL in one of the 1.6.0 migrations. I'll fix this ASAP.

**Comment by nathanwoulfe** [comment]
@mamray I've published a nightly build for 1.6.1, which I believe fixes the issue - I've installed locally onto SQLCE and SQL server, both installs completed without issue. If you could please try again and confirm the issue is fixed, I'll push out a proper release.

**Comment by mamray** [comment]
I will check the fix and will post the result of the test here. Thanks)

**Comment by mamray** [comment]
@nathanwoulfe I'm sorry, but where do I get that 1.6.1 version? I do not see any links here and nuget is still of 1.6.0. TA

**Comment by nathanwoulfe** [comment]
@mamray it's a prerelease, so you'll need to tick the 'include prerelease' box in the nuget package manager in visual studio, or should be able to install via the console if you specify the version, 1.6.1-beta-000566

**Comment by mamray** [comment]
@nathanwoulfe Yes, confirm, 1.6.1 works fine. Thanks.

**Comment by nathanwoulfe** [comment]
@mamray good to hear! I'll finalise the proper release today.
