### ISSUE TITLE
Publish buttons disappear in release mode

### ISSUE THREAD

**Issue by callumbwhyte** [nathanwoulfe/Plumber-2#9]
When running Umbraco in release mode, by setting `<compilation debug="false" ... />` in the `web.config`, the backoffice JavaScript throws an error and in turn causes the "save and publish" buttons on content items to disappear.

When in release mode Umbraco bundles and minifies every asset in the backoffice via ClientDependencyFramework, it seems this is what's causing the issue.

The error in the console is as follows:

```
Error: [ng:areq] Argument 'scope' is required
```

Looks like it's blowing up inside the content app `Workflow.App.Controller`

**Comment by nathanwoulfe** [comment]
Ah, yes. `$compileProvider.debugInfoEnabled` must be set to false in release mode, which makes `.scope()` return null. Should be able to get the scope I need off editorState, hopefully.

This change was made to manage the inlining of directive templates - I'd previously used an interceptor to swap out the footer buttons html with my own markup, but needed an alternative when the template files were removed. Guess I need an alternative alternative.

**Comment by nathanwoulfe** [comment]
Get some v1.0.6 in ya guts - have had to do some disgusting scope traversal to get the editor form scope from the app, but it's disgusting and it works. 

Bit annoying to lose extension points compared to Umbraco 7, but it is what it is.

**Comment by callumbwhyte** [comment]
Looks like it's fixed, thanks!

Perhaps we need to PR some extension points / hooks into V8 for a better solution to this. I also had to override these recently and decided an interceptor was the only "nice" way...

**Comment by nathanwoulfe** [comment]
Using a do...while loop to traverse up through parent scopes is not something I'm super proud of. Would be great to have a cleaner, saner way
