### ISSUE TITLE
Workflow Cancelled emails not sending

### ISSUE THREAD

**Issue by NikRimington** [nathanwoulfe/Plumber-2#93]
**Describe the bug**
When I cancel a workflow, I expect the Workflow cancelled email to get sent out to the approval group to inform them it was cancelled.

**To Reproduce**
1. Set up an approval group
2. Request publish on a page protected by the approval group
3. Wait for the Approval Request notification to arrive
4. Cancel the request

**Expected behavior**
I would expect to get the Workflow Cancelled notification as used to happen

**Plumber version**
1.6.5

**Licensed version?**
Yes

**Additional context**
Looking in the Umbraco logs the following error is being logged:

```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Plumber.Core.Models.Email.HtmlEmailModel.get_Summary() in D:\a\1\s\Plumber.Core\Models\Email\HtmlEmailModel.cs:line 32
```

**Comment by nathanwoulfe** [comment]
Thanks @NikRimington, I'll get this fixed up today. 1.6.6 isn't far away, but I'll publish as a nightly too.

**Comment by nathanwoulfe** [comment]
@NikRimington does the approval group by chance have a group email configured?

**Comment by NikRimington** [comment]
It does yes, I can't recall if my local test one does though.

**Comment by nathanwoulfe** [comment]
Makes sense in that case - because the email body is localized, it expects the recipient to have a culture. If the recipient is a group email, there's no culture. For now, I'll set that to the current backoffice culture (in v1.6.6), but will add a language setting to the user group to allow per-group email localization (will be in the v2.0.0 release)

**Comment by nathanwoulfe** [comment]
Beta building now, will be on NuGet in 30 or so
