### ISSUE TITLE
View differences not working with license

### ISSUE THREAD

**Issue by 37gears** [nathanwoulfe/Plumber-2#95]
**Describe the bug**
when you click view differences an error occurs:

An error occured
Error getting changes for workflow instance f2920444-1291-444f-866d-080d77728849: Current license does not include this feature

Exception Details
InvalidLicenseException: Error getting changes for workflow instance f2920444-1291-444f-866d-080d77728849: Current license does not include this feature
Stacktrace
at Plumber.Core.Licensing.LicensedFeature() in D:\a\1\s\Plumber.Core\Licensing.cs:line 31
   at Plumber.Web.Api.InstancesController.GetDiff(Guid guid) in D:\a\1\s\Plumber.Web\Api\InstancesController.cs:line 146

**To Reproduce**
1. click view differences on active workflow or history
2. See error

**Expected behavior**
see workflow

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version N/a

**Plumber version**
1.6.6.820

**Licensed version?**
yes - Customer ID: cus_JvQgyXVFTrAbaI

**Additional context**

**Comment by nathanwoulfe** [comment]
Hi @37gears, that's a bit of a strange one - do you have issues accessing other licensed features (ie can you create more than 5 approval groups)?

Looking at the trace, this is happening in a check for license impersonation, which makes me think that perhaps you've deployed the test.lic file into production?

Could you also let me know the licensed URL and the URL where the error occurs?

**Comment by 37gears** [comment]
using on www.scag.gov, license is scag.gov - we can use all other license features but noticed we can only add 5 users to a group (we have more than 5 groups working fine)

<img width="345" alt="Screen Shot 2021-08-23 at 5 02 11 PM" src="https://user-images.githubusercontent.com/34718311/130519274-1238dcbe-4f6c-46b9-a352-bb09ddbdec2a.png">

**Comment by nathanwoulfe** [comment]
Ok, that's a start. I'll have a look into this today, can't see anything obvious so far... The five user limit shouldn't be a thing anymore, that was removed in a previous version, will need to check why that's happening.

Any chance that there's a test license in production? That should show a different domain message if so, but could be a possibility and would explain the licensing error.

**Comment by 37gears** [comment]
no we uploaded the files and then entered them in the admin - same issue both ways

**Comment by nathanwoulfe** [comment]
@37gears pretty sure I've tracked this down - looks the the HttpContext was being cached on startup, which meant later when determining the application URL it was comparing against an incorrect value. There's a nightly building now, which should resolve your issue and also the max-members bug.

Release will be on NuGet in 30 minutes or so, `v1.6.7-beta-000823`. Please let me know if this fixes the issue, and I'll push a release.

**Comment by 37gears** [comment]
that fixed everything.  Thanks for your quick response

**Comment by lordscarlet** [comment]
This is happening to us as well, FWIW. Will look at updating our version.

**Comment by nathanwoulfe** [comment]
@lordscarlet if you want to hold off for a few hours I'll have the 1.6.7 version released. 

I'd fixed the issue in v2, but hadn't backported to v1. Sooner I can get v2 out the better, trying to keep two branches in sync sucks.

**Comment by lordscarlet** [comment]
> @lordscarlet if you want to hold off for a few hours I'll have the 1.6.7 version released.
> 
> I'd fixed the issue in v2, but hadn't backported to v1. Sooner I can get v2 out the better, trying to keep two branches in sync sucks.

we have some internal changes to the js/html still that we have to apply teach time, so we always take a bit to pull the trigger on an update anyway.

if its a cache issue, is it possible to restart the app or anything in the short term to clear the bug temporarily?

**Comment by nathanwoulfe** [comment]
Unfortunately not - there's a reference to HttpContext which gets stuck in a static class, and used when getting the application URL. Since the reference was cached way early, the Umbraco application URL doesn't yet exist, so the license check fails. 

1.6.7 is building now, will be ready when you are.
