### ISSUE TITLE
Multi Url Picker value doesnt appear to save in workflow.

### ISSUE THREAD

**Issue by wilbert-seansly** [nathanwoulfe/Plumber-2#99]
Whenever I add a field of type Multi Url Picker (Umbraco.MultiUrlPicker), the value doesn't appear save on an item in a workflow.  I'm just using a trial license right now.  Umbraco 8.14.2

If I remove the item from the workflow, I can then add a value to the field and it saves correctly.

**Comment by nathanwoulfe** [comment]
Hi @wilbert-seansly I'm not sure I follow - are you meaning you're adding a new property of type Umbraco.MultiUrlPicker to a content type where an instance of that content type is in a workflow? Or adding a value to an existing url picker on a node already in a workflow? Either way, Plumber doesn't change how content is saved, other than to optionally prevent content edits in an active workflow.

Can you provide a more detailed example?

**Comment by nathanwoulfe** [comment]
@wilbert-seansly I think I've found your issue:
- edit a content item
- do NOT save
- request publish
- workflow reports as complete, but data is not saved

Will have a fix in 2.0.2

**Comment by nathanwoulfe** [comment]
Fixed in v2.0.2
